_itemsSource["weapons_base"] = {
	{
		name = "WEAPON_BULLPUPSHOTGUN",
		label = "Grapple Gun",
		ammoType = "NOT_USABLE",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 90),
		noSerial = true,
		type = 2,
		rarity = 7,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
		staticMetadata = {
			WeaponTint = 2,
		},
	},
	{
		name = "WEAPON_BULLPUPSHOTGUN_PD",
		label = "PD Grapple Gun",
		iconOverride = "WEAPON_BULLPUPSHOTGUN",
		weapon = "WEAPON_BULLPUPSHOTGUN",
		ammoType = "NOT_USABLE",
		qualification = "PD_GRAPPLE",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 90),
		noSerial = true,
		type = 2,
		rarity = 7,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
		staticMetadata = {
			WeaponTint = 2,
		},
	},
	{
		name = "WEAPON_SMG",
		label = "SMG",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_MP5",
		weapon = "WEAPON_MP5",
		iconOverride = "WEAPON_SMG",
		label = "SB54",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_BALL",
		label = "Ball",
		ammoType = "AMMO_BALL",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		isThrowable = true,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_SNOWBALL",
		label = "Snowball",
		ammoType = "AMMO_SNOWBALL",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		isThrowable = true,
		durability = (60 * 60 * 24),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0,
	},
	{
		name = "WEAPON_GRENADE",
		label = "Grenade",
		ammoType = "AMMO_GRENADE",
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_BZGAS",
		label = "BZ Gas",
		ammoType = "AMMO_BZGAS",
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_MOLOTOV",
		label = "Molotov",
		ammoType = "AMMO_MOLOTOV",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 5,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2,
	},
	{
		name = "WEAPON_STICKYBOMB",
		label = "C4",
		ammoType = "AMMO_STICKYBOMB",
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = "WEAPON_PROXMINE",
		label = "Proximity Mine",
		ammoType = "AMMO_PROXMINE",
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = "WEAPON_PIPEBOMB",
		label = "Pipe Bomb",
		ammoType = "AMMO_PIPEBOMB",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = "WEAPON_SMOKEGRENADE",
		label = "Smoke Grenade",
		ammoType = "AMMO_SMOKEGRENADE",
		qualification = "PD_SWAT",
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		storeStack = 1,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 1,
	},
	{
		name = "WEAPON_FLASHBANG",
		label = "Flashbang",
		ammoType = "AMMO_FLASH",
		qualification = "PD_SWAT",
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		storeStack = 1,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 1,
	},
	{
		name = "WEAPON_FLARE",
		label = "Flare",
		ammoType = "AMMO_FLARE",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 14),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_FIREEXTINGUISHER",
		label = "Fire Extinguisher",
		ammoType = "AMMO_FIREEXTINGUISHER",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 21),
		type = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_PETROLCAN",
		label = "Petrol Can",
		ammoType = "AMMO_PETROLCAN",
		requiresLicense = false,
		noSerial = true,
		price = 150,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_CROWBAR",
		label = "Crowbar",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_BAT",
		label = "Baseball Bat",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_SHOVEL",
		label = "Shovel",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_DAGGER",
		label = "Dagger",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_MACHETE",
		label = "Machete",
		requiresLicense = false,
		noSerial = true,
		price = 700,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_PONY",
		label = "Pony",
		requiresLicense = false,
		noSerial = true,
		price = 700,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_KNIFE",
		label = "Knife",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8.5,
	},
	{
		name = "WEAPON_SWITCHBLADE",
		label = "Switchblade",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8,
	},
	{
		name = "WEAPON_BOTTLE",
		label = "Broken Bottle",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8,
	},
	{
		name = "WEAPON_WRENCH",
		label = "Pipe Wrench",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_BATTLEAXE",
		label = "Battle Axe",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 18,
	},
	{
		name = "WEAPON_HATCHET",
		label = "Hatchet",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 18,
	},
	{
		name = "WEAPON_STONE_HATCHET",
		label = "Stone Hatchet",
		requiresLicense = false,
		noSerial = true,
		price = 300,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 12,
	},
	{
		name = "WEAPON_HAMMER",
		label = "Hammer",
		requiresLicense = false,
		noSerial = true,
		price = 500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_GOLFCLUB",
		label = "Golf Club",
		requiresLicense = false,
		noSerial = true,
		price = 500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = "WEAPON_KNUCKLE",
		label = "Knuckle Dusters",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 7.5,
	},
	{
		name = "WEAPON_POOLCUE",
		label = "Pool Cue",
		requiresLicense = false,
		noSerial = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_FLASHLIGHT",
		label = "Flashlight",
		requiresLicense = false,
		noSerial = true,
		price = 75,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8,
	},
	{
		name = "WEAPON_NIGHTSTICK",
		label = "Nightstick",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8,
	},
	{
		name = "WEAPON_PISTOL",
		label = "Pistol",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 2000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_COMBATPISTOL",
		label = "Combat Pistol",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_APPISTOL",
		label = "F18 Auto",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_VINTAGEPISTOL",
		label = "Vintage Pistol",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 5500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_HEAVYPISTOL",
		label = "Heavy Pistol",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_SNSPISTOL",
		label = "SNS Pistol",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 8,
		gun = true,
	},
	{
		name = "WEAPON_SNSPISTOL_MK2",
		label = "SNS Pistol MK2",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 4500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 8,
		gun = true,
	},
	{
		name = "WEAPON_FLAREGUN",
		label = "Flaregun",
		ammoType = "AMMO_FLAREGUN",
		requiresLicense = false,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_MARKSMANPISTOL",
		label = "Marksman Pistol",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 7500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_REVOLVER",
		label = "Revolver",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 7000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_REVOLVER_MK2",
		label = "Revolver MK2",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 7000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_DOUBLEACTION",
		label = "Double Action Revolver",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 8000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_PISTOL50",
		label = "Desert Eagle",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_PISTOL_MK2",
		label = "PD 9MM",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 2500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_MICROSMG",
		weapon = "WEAPON_MAC10",
		label = "MAC 10",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "WEAPON_MINISMG",
		label = "Mini SMG",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isDestroyed = false,
		isStackable = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "WEAPON_SMG_MK2",
		label = "SMG Mk2",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "WEAPON_ASSAULTSMG",
		label = "F90",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_COMBATPDW",
		label = "Combat PDW",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MACHINEPISTOL",
		label = "TEC-9",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "WEAPON_GUSENBERG",
		label = "Tommy Gun",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MG",
		label = "PKM",
		ammoType = "AMMO_MG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
		gun = true,
	},
	{
		name = "WEAPON_COMBATMG",
		label = "LMG",
		ammoType = "AMMO_MG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
		gun = true,
	},
	{
		name = "WEAPON_COMBATMG_MK2",
		label = "LMG MK2",
		ammoType = "AMMO_MG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
		gun = true,
	},
	{
		name = "WEAPON_MUSKET",
		label = "Musket",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_BEANBAG",
		label = "Beanbag Gun",
		ammoType = "AMMO_SHOTGUN",
		qualification = "PD_BEANBAG",
		requiresLicense = true,
		price = 300,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_SAWNOFFSHOTGUN",
		label = "Sawnoff Shotgun",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "WEAPON_PUMPSHOTGUN",
		label = "Pump Shotgun",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_PUMPSHOTGUN_MK2",
		label = "PD Shotgun",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_ASSAULTSHOTGUN",
		label = "SB 12G Assault",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_DBSHOTGUN",
		label = "Double Barrel Shotgun",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_HEAVYSHOTGUN",
		label = "Assault Shotgun",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_AUTOSHOTGUN",
		label = "Auto Shotty",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_ASSAULTRIFLE",
		label = "AK-47",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_ASSAULTRIFLE_MK2",
		label = "AK-12",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_CARBINERIFLE",
		label = "PD .556",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_CARBINERIFLE_MK2",
		label = "PD .762",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_COMPACTRIFLE",
		label = "Draco",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_BULLPUPRIFLE",
		label = "Bullpup Rifle",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_BULLPUPRIFLE_MK2",
		label = "Bullpup Rifle Mk2",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_ADVANCEDRIFLE",
		label = "Groza",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_SPECIALCARBINE",
		label = "F36D",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_SPECIALCARBINE_MK2",
		label = "F36D Mk2",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MARKSMANRIFLE",
		label = "F39 MMR",
		ammoType = "AMMO_SNIPER",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MARKSMANRIFLE_MK2",
		label = "F39 MMR mk2",
		ammoType = "AMMO_SNIPER",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_HEAVYSNIPER",
		label = ".50 Sniper",
		ammoType = "AMMO_SNIPER",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_HEAVYSNIPER_MK2",
		label = "BFG-50A",
		ammoType = "AMMO_SNIPER",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_GRENADELAUNCHER_SMOKE",
		label = "S Grenade Launcher",
		ammoType = "AMMO_GRENADELAUNCHER_SMOKE",
		requiresLicense = true,
		price = 100000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
	},
	{
		name = "WEAPON_FIREWORK",
		label = "Firework Launcher",
		ammoType = "AMMO_FIREWORK",
		requiresLicense = false,
		price = 100000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 20,
	},
	{
		name = "WEAPON_STUNGUN",
		label = "Stun Gun",
		ammoType = "AMMO_STUNGUN",
		requiresLicense = false,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
	 	metalic = true,
	 	weight = 1,
	},
}
